"""One-shot script: expands skill_taxonomy.json from ~70 to 300+ skills."""
import json, pathlib

OUT = pathlib.Path(__file__).parent / "app" / "data" / "skill_taxonomy.json"

# Load existing
with open(OUT) as f:
    data = json.load(f)

skills = data["skills"]

# Helper
def add(key, canonical, cat, aliases=None, related=None, w=0.5):
    if key not in skills:
        skills[key] = {"canonical": canonical, "category": cat,
                       "aliases": aliases or [], "related": related or [],
                       "importance_weight": w}

# ── PROGRAMMING ──────────────────────────────────────────
add("lua", "Lua", "programming", ["lua lang"], ["Game Development"], 0.5)
add("perl", "Perl", "programming", ["perl5", "perl6"], ["Regex"], 0.45)
add("haskell", "Haskell", "programming", [], ["Functional Programming"], 0.5)
add("elixir", "Elixir", "programming", [], ["Phoenix", "Erlang"], 0.55)
add("erlang", "Erlang", "programming", ["otp"], ["Elixir", "Distributed Systems"], 0.5)
add("clojure", "Clojure", "programming", [], ["Java", "Functional Programming"], 0.5)
add("f#", "F#", "programming", ["fsharp", "f sharp"], [".NET"], 0.45)
add("objective-c", "Objective-C", "programming", ["objc", "obj-c"], ["iOS", "Swift"], 0.5)
add("matlab", "MATLAB", "programming", [], ["Signal Processing", "Statistics"], 0.5)
add("julia", "Julia", "programming", ["julia lang"], ["Data Science", "NumPy"], 0.5)
add("groovy", "Groovy", "programming", [], ["Java", "Gradle", "Jenkins"], 0.45)
add("powershell", "PowerShell", "programming", ["ps1", "pwsh"], ["Windows", "Azure"], 0.5)
add("solidity", "Solidity", "programming", [], ["Ethereum", "Smart Contracts", "Blockchain"], 0.6)
add("assembly", "Assembly", "programming", ["asm", "x86", "arm assembly"], ["Embedded Systems"], 0.4)
add("vba", "VBA", "programming", ["visual basic", "vb.net", "visual basic for applications"], ["Excel", "Microsoft Office"], 0.35)
add("cobol", "COBOL", "programming", [], ["Mainframe"], 0.3)
add("fortran", "Fortran", "programming", [], ["HPC", "Scientific Computing"], 0.3)
add("prolog", "Prolog", "programming", [], ["Logic Programming", "AI"], 0.3)

# ── FRAMEWORKS & LIBRARIES ──────────────────────────────
add("nuxt.js", "Nuxt.js", "framework", ["nuxtjs", "nuxt js", "nuxt"], ["Vue", "TypeScript"], 0.6)
add("gatsby", "Gatsby", "framework", ["gatsbyjs"], ["React", "GraphQL"], 0.5)
add("remix", "Remix", "framework", ["remix.run"], ["React", "TypeScript"], 0.55)
add("astro", "Astro", "framework", ["astro.build"], ["JavaScript"], 0.5)
add("tailwind css", "Tailwind CSS", "framework", ["tailwind", "tailwindcss"], ["CSS", "Frontend"], 0.7)
add("bootstrap", "Bootstrap", "framework", ["bootstrap 5"], ["CSS", "Frontend"], 0.55)
add("material ui", "Material UI", "framework", ["mui", "material-ui"], ["React"], 0.6)
add("chakra ui", "Chakra UI", "framework", ["chakra"], ["React"], 0.5)
add("jquery", "jQuery", "framework", ["jquery"], ["JavaScript"], 0.4)
add("redux", "Redux", "framework", ["redux toolkit", "rtk"], ["React", "State Management"], 0.65)
add("pydantic", "Pydantic", "framework", [], ["Python", "FastAPI"], 0.6)
add("sqlalchemy", "SQLAlchemy", "framework", ["sql alchemy"], ["Python", "PostgreSQL", "ORM"], 0.6)
add("hibernate", "Hibernate", "framework", [], ["Java", "ORM", "Spring Boot"], 0.6)
add("nestjs", "NestJS", "framework", ["nest.js", "nest js"], ["TypeScript", "Node.js"], 0.65)
add("fastify", "Fastify", "framework", [], ["Node.js", "JavaScript"], 0.5)
add("gin", "Gin", "framework", ["gin-gonic"], ["Go", "REST API"], 0.55)
add("phoenix", "Phoenix", "framework", [], ["Elixir", "WebSockets"], 0.5)
add("three.js", "Three.js", "framework", ["threejs"], ["JavaScript", "WebGL", "3D"], 0.5)
add("electron", "Electron", "framework", ["electronjs"], ["JavaScript", "Desktop Apps"], 0.55)
add("unity", "Unity", "framework", ["unity3d", "unity engine"], ["C#", "Game Development"], 0.6)
add("unreal engine", "Unreal Engine", "framework", ["ue4", "ue5", "unreal"], ["C++", "Game Development"], 0.55)
add("celery", "Celery", "framework", [], ["Python", "Redis", "Task Queue"], 0.55)
add("pytest", "pytest", "framework", ["py test"], ["Python", "Testing"], 0.55)
add("jest", "Jest", "framework", ["jestjs"], ["JavaScript", "Testing"], 0.55)
add("cypress", "Cypress", "framework", ["cypress.io"], ["Testing", "JavaScript", "E2E Testing"], 0.55)
add("selenium", "Selenium", "framework", ["selenium webdriver"], ["Testing", "Automation"], 0.55)
add("storybook", "Storybook", "framework", [], ["React", "UI Components"], 0.45)
add("webpack", "Webpack", "framework", [], ["JavaScript", "Bundling"], 0.5)
add("vite", "Vite", "framework", ["vitejs"], ["JavaScript", "Bundling"], 0.55)
add("swagger", "Swagger", "framework", ["openapi", "swagger ui"], ["REST API", "API Documentation"], 0.5)
add("grpc", "gRPC", "framework", ["grpc", "google rpc"], ["Microservices", "Protobuf"], 0.65)
add("rxjs", "RxJS", "framework", ["reactive extensions"], ["Angular", "TypeScript"], 0.5)
add("keras", "Keras", "framework", [], ["TensorFlow", "Deep Learning", "Python"], 0.7)
add("hugging face", "Hugging Face", "framework", ["huggingface", "hf", "transformers library"], ["NLP", "LLM", "Transformers"], 0.75)
add("langchain", "LangChain", "framework", ["lang chain"], ["LLM", "RAG", "Python"], 0.7)
add("streamlit", "Streamlit", "framework", [], ["Python", "Data Science", "Dashboard"], 0.5)
add("gradio", "Gradio", "framework", [], ["Python", "Machine Learning", "UI"], 0.45)
add("dbt", "dbt", "framework", ["data build tool"], ["SQL", "Data Engineering", "Analytics"], 0.6)

# ── DATABASES ────────────────────────────────────────────
add("mariadb", "MariaDB", "database", ["maria db"], ["MySQL", "SQL"], 0.55)
add("neo4j", "Neo4j", "database", [], ["Graph Database", "Cypher"], 0.55)
add("couchdb", "CouchDB", "database", ["couch db", "apache couchdb"], ["NoSQL"], 0.4)
add("firestore", "Firestore", "database", ["cloud firestore"], ["Firebase", "GCP", "NoSQL"], 0.55)
add("firebase", "Firebase", "database", ["google firebase"], ["GCP", "Firestore", "Mobile Development"], 0.6)
add("supabase", "Supabase", "database", [], ["PostgreSQL", "Firebase Alternative"], 0.55)
add("cockroachdb", "CockroachDB", "database", ["cockroach db"], ["Distributed SQL"], 0.45)
add("influxdb", "InfluxDB", "database", ["influx db"], ["Time Series", "Monitoring"], 0.45)
add("oracle", "Oracle Database", "database", ["oracle db", "oracle sql", "plsql", "pl/sql"], ["SQL", "Enterprise"], 0.6)
add("snowflake", "Snowflake", "database", [], ["Data Warehouse", "SQL", "Cloud"], 0.7)
add("bigquery", "BigQuery", "database", ["big query", "google bigquery"], ["GCP", "SQL", "Data Warehouse"], 0.65)
add("redshift", "Redshift", "database", ["amazon redshift", "aws redshift"], ["AWS", "Data Warehouse", "SQL"], 0.6)

# ── CLOUD ────────────────────────────────────────────────
add("ecs", "ECS", "cloud", ["aws ecs", "amazon ecs"], ["AWS", "Docker", "Container"], 0.6)
add("eks", "EKS", "cloud", ["aws eks", "amazon eks"], ["AWS", "Kubernetes"], 0.6)
add("fargate", "Fargate", "cloud", ["aws fargate"], ["AWS", "Serverless", "Container"], 0.55)
add("cloudformation", "CloudFormation", "cloud", ["aws cloudformation", "cfn"], ["AWS", "Infrastructure as Code"], 0.6)
add("cloud functions", "Cloud Functions", "cloud", ["google cloud functions", "gcf"], ["GCP", "Serverless"], 0.55)
add("cloud run", "Cloud Run", "cloud", ["google cloud run"], ["GCP", "Container", "Serverless"], 0.55)
add("azure functions", "Azure Functions", "cloud", [], ["Azure", "Serverless"], 0.55)
add("azure devops", "Azure DevOps", "cloud", ["ado"], ["Azure", "CI/CD"], 0.6)
add("sagemaker", "SageMaker", "cloud", ["aws sagemaker", "amazon sagemaker"], ["AWS", "Machine Learning"], 0.6)
add("cloudflare", "Cloudflare", "cloud", ["cloudflare workers"], ["CDN", "Edge Computing"], 0.55)
add("vercel", "Vercel", "cloud", [], ["Next.js", "Frontend Deployment"], 0.55)
add("netlify", "Netlify", "cloud", [], ["Frontend Deployment", "CI/CD"], 0.45)
add("heroku", "Heroku", "cloud", [], ["PaaS", "Deployment"], 0.4)
add("digitalocean", "DigitalOcean", "cloud", ["digital ocean"], ["Cloud Computing", "VPS"], 0.4)
add("serverless", "Serverless", "cloud", ["serverless framework", "serverless architecture"], ["Lambda", "Cloud Functions"], 0.65)

# ── DEVOPS & TOOLS ───────────────────────────────────────
add("helm", "Helm", "devops", ["helm charts"], ["Kubernetes", "DevOps"], 0.6)
add("gitlab ci", "GitLab CI", "devops", ["gitlab ci/cd", "gitlab pipelines"], ["CI/CD", "GitLab"], 0.6)
add("argocd", "ArgoCD", "devops", ["argo cd", "argo"], ["Kubernetes", "GitOps", "CI/CD"], 0.55)
add("prometheus", "Prometheus", "devops", [], ["Monitoring", "Grafana", "Kubernetes"], 0.6)
add("grafana", "Grafana", "devops", [], ["Monitoring", "Prometheus", "Dashboard"], 0.55)
add("datadog", "Datadog", "devops", ["data dog"], ["Monitoring", "APM", "Observability"], 0.55)
add("new relic", "New Relic", "devops", ["newrelic"], ["APM", "Monitoring"], 0.5)
add("splunk", "Splunk", "devops", [], ["Log Analysis", "SIEM", "Monitoring"], 0.5)
add("elk stack", "ELK Stack", "devops", ["elk", "elastic stack"], ["Elasticsearch", "Logstash", "Kibana"], 0.55)
add("pulumi", "Pulumi", "devops", [], ["Infrastructure as Code", "AWS", "TypeScript"], 0.5)
add("vagrant", "Vagrant", "devops", [], ["Virtualization", "DevOps"], 0.4)
add("packer", "Packer", "devops", ["hashicorp packer"], ["DevOps", "Image Building"], 0.45)
add("consul", "Consul", "devops", ["hashicorp consul"], ["Service Mesh", "Microservices"], 0.45)
add("istio", "Istio", "devops", [], ["Service Mesh", "Kubernetes"], 0.5)
add("sonarqube", "SonarQube", "devops", ["sonar"], ["Code Quality", "Static Analysis"], 0.45)
add("jira", "JIRA", "devops", ["atlassian jira"], ["Agile", "Project Management"], 0.5)
add("confluence", "Confluence", "devops", [], ["Documentation", "Atlassian"], 0.35)
add("npm", "npm", "devops", ["node package manager"], ["Node.js", "JavaScript"], 0.5)
add("yarn", "Yarn", "devops", [], ["Node.js", "JavaScript"], 0.45)
add("maven", "Maven", "devops", ["apache maven"], ["Java", "Build Tool"], 0.55)
add("gradle", "Gradle", "devops", [], ["Java", "Kotlin", "Build Tool"], 0.55)
add("make", "Make", "devops", ["makefile", "gnu make"], ["Build Tool", "C"], 0.4)
add("cmake", "CMake", "devops", [], ["C++", "Build Tool"], 0.45)

# ── ML / AI / DATA ──────────────────────────────────────
add("xgboost", "XGBoost", "ml_ai", ["xg boost"], ["Machine Learning", "Gradient Boosting"], 0.7)
add("lightgbm", "LightGBM", "ml_ai", ["light gbm"], ["Machine Learning", "Gradient Boosting"], 0.6)
add("catboost", "CatBoost", "ml_ai", [], ["Machine Learning", "Gradient Boosting"], 0.55)
add("bert", "BERT", "ml_ai", ["bert model"], ["NLP", "Transformers", "Deep Learning"], 0.7)
add("gpt", "GPT", "ml_ai", ["gpt-4", "gpt-3", "chatgpt", "openai gpt"], ["LLM", "NLP"], 0.75)
add("stable diffusion", "Stable Diffusion", "ml_ai", [], ["Generative AI", "Computer Vision"], 0.5)
add("rag", "RAG", "ml_ai", ["retrieval augmented generation"], ["LLM", "NLP", "Vector Database"], 0.65)
add("fine-tuning", "Fine-tuning", "ml_ai", ["fine tuning", "model fine-tuning"], ["LLM", "Machine Learning"], 0.6)
add("prompt engineering", "Prompt Engineering", "ml_ai", ["prompt design"], ["LLM", "NLP"], 0.6)
add("mlops", "MLOps", "ml_ai", ["ml ops", "ml operations"], ["Machine Learning", "DevOps", "CI/CD"], 0.7)
add("mlflow", "MLflow", "ml_ai", ["ml flow"], ["MLOps", "Model Tracking"], 0.55)
add("kubeflow", "Kubeflow", "ml_ai", ["kube flow"], ["MLOps", "Kubernetes"], 0.5)
add("spacy", "spaCy", "ml_ai", [], ["NLP", "Python", "NER"], 0.6)
add("nltk", "NLTK", "ml_ai", [], ["NLP", "Python", "Text Processing"], 0.5)
add("scipy", "SciPy", "ml_ai", [], ["Python", "NumPy", "Scientific Computing"], 0.55)
add("matplotlib", "Matplotlib", "ml_ai", ["mpl"], ["Python", "Data Visualization"], 0.5)
add("seaborn", "Seaborn", "ml_ai", [], ["Python", "Data Visualization", "Matplotlib"], 0.45)
add("plotly", "Plotly", "ml_ai", [], ["Data Visualization", "Python", "Dashboard"], 0.5)
add("tableau", "Tableau", "ml_ai", [], ["Data Visualization", "BI", "Dashboard"], 0.6)
add("power bi", "Power BI", "ml_ai", ["powerbi", "microsoft power bi"], ["Data Visualization", "BI"], 0.55)
add("airflow", "Apache Airflow", "ml_ai", ["airflow"], ["Data Engineering", "ETL", "Python"], 0.65)
add("hadoop", "Hadoop", "ml_ai", ["apache hadoop", "hdfs"], ["Big Data", "MapReduce"], 0.55)
add("data engineering", "Data Engineering", "ml_ai", ["data engineer"], ["ETL", "SQL", "Python"], 0.7)
add("etl", "ETL", "ml_ai", ["extract transform load", "elt"], ["Data Engineering", "SQL"], 0.6)
add("feature engineering", "Feature Engineering", "ml_ai", [], ["Machine Learning", "Data Science"], 0.55)
add("statistics", "Statistics", "ml_ai", ["statistical analysis", "statistical modeling"], ["Data Science", "R", "Python"], 0.6)
add("a/b testing", "A/B Testing", "ml_ai", ["ab testing", "split testing"], ["Statistics", "Data Science"], 0.5)
add("reinforcement learning", "Reinforcement Learning", "ml_ai", ["rl"], ["Machine Learning", "Deep Learning"], 0.6)
add("time series", "Time Series Analysis", "ml_ai", ["time series forecasting", "time series"], ["Statistics", "Machine Learning"], 0.55)
add("vector database", "Vector Database", "ml_ai", ["vector db", "vector store"], ["RAG", "Embeddings", "LLM"], 0.6)
add("pinecone", "Pinecone", "ml_ai", [], ["Vector Database", "RAG"], 0.5)
add("weaviate", "Weaviate", "ml_ai", [], ["Vector Database", "RAG"], 0.45)
add("chromadb", "ChromaDB", "ml_ai", ["chroma"], ["Vector Database", "RAG"], 0.45)

# ── OTHER / CONCEPTS ─────────────────────────────────────
add("oauth", "OAuth", "other", ["oauth2", "oauth 2.0"], ["Authentication", "Security"], 0.6)
add("jwt", "JWT", "other", ["json web token", "json web tokens"], ["Authentication", "Security"], 0.6)
add("websockets", "WebSockets", "other", ["websocket", "web socket", "ws"], ["Real-time", "Socket.IO"], 0.55)
add("socket.io", "Socket.IO", "other", ["socketio"], ["WebSockets", "Real-time", "Node.js"], 0.5)
add("html", "HTML", "other", ["html5"], ["CSS", "Frontend"], 0.5)
add("css", "CSS", "other", ["css3", "cascading style sheets"], ["HTML", "Frontend", "Tailwind CSS"], 0.5)
add("sass", "Sass", "other", ["scss"], ["CSS", "Frontend"], 0.45)
add("responsive design", "Responsive Design", "other", ["responsive web design", "rwd", "mobile-first"], ["CSS", "Frontend"], 0.5)
add("accessibility", "Accessibility", "other", ["a11y", "wcag", "web accessibility"], ["Frontend", "UX"], 0.5)
add("seo", "SEO", "other", ["search engine optimization"], ["Frontend", "Marketing"], 0.4)
add("web scraping", "Web Scraping", "other", ["web crawling", "scraping"], ["Python", "BeautifulSoup", "Scrapy"], 0.5)
add("blockchain", "Blockchain", "other", ["distributed ledger"], ["Smart Contracts", "Solidity", "Web3"], 0.55)
add("web3", "Web3", "other", ["web 3.0"], ["Blockchain", "Ethereum", "Solidity"], 0.5)
add("cybersecurity", "Cybersecurity", "other", ["cyber security", "information security", "infosec"], ["Penetration Testing", "Network Security"], 0.6)
add("penetration testing", "Penetration Testing", "other", ["pen testing", "pentest", "ethical hacking"], ["Cybersecurity"], 0.5)
add("networking", "Networking", "other", ["computer networking", "tcp/ip", "network protocols"], ["Linux", "Cloud"], 0.5)
add("api design", "API Design", "other", ["api architecture"], ["REST API", "GraphQL", "gRPC"], 0.65)
add("design patterns", "Design Patterns", "other", ["software design patterns", "gang of four"], ["OOP", "System Design"], 0.6)
add("oop", "OOP", "other", ["object oriented programming", "object-oriented"], ["Design Patterns", "Java", "Python"], 0.55)
add("functional programming", "Functional Programming", "other", ["fp"], ["Haskell", "Elixir", "Scala"], 0.5)
add("tdd", "TDD", "other", ["test driven development", "test-driven development"], ["Testing", "Unit Testing"], 0.55)
add("unit testing", "Unit Testing", "other", ["unit tests"], ["Testing", "TDD", "pytest", "Jest"], 0.6)
add("integration testing", "Integration Testing", "other", ["integration tests"], ["Testing", "CI/CD"], 0.55)
add("distributed systems", "Distributed Systems", "other", ["distributed computing"], ["Microservices", "System Design"], 0.7)
add("event-driven architecture", "Event-Driven Architecture", "other", ["event driven", "eda"], ["Kafka", "Microservices", "CQRS"], 0.6)
add("cqrs", "CQRS", "other", ["command query responsibility segregation"], ["Event-Driven Architecture", "DDD"], 0.5)
add("ddd", "DDD", "other", ["domain driven design", "domain-driven design"], ["System Design", "Microservices"], 0.55)
add("devops", "DevOps", "other", ["dev ops"], ["CI/CD", "Docker", "Kubernetes", "AWS"], 0.75)
add("site reliability engineering", "SRE", "other", ["sre", "site reliability"], ["DevOps", "Monitoring"], 0.65)
add("infrastructure as code", "Infrastructure as Code", "other", ["iac"], ["Terraform", "CloudFormation", "Pulumi"], 0.65)
add("caching", "Caching", "other", ["cache strategies", "cache invalidation"], ["Redis", "CDN", "Performance"], 0.55)
add("load balancing", "Load Balancing", "other", ["load balancer"], ["Nginx", "AWS", "Scalability"], 0.5)
add("data modeling", "Data Modeling", "other", ["data model", "database design", "schema design"], ["SQL", "NoSQL"], 0.6)
add("orm", "ORM", "other", ["object relational mapping"], ["SQLAlchemy", "Hibernate", "Database"], 0.5)
add("regex", "Regex", "other", ["regular expressions", "regexp"], ["Text Processing"], 0.4)
add("json", "JSON", "other", ["javascript object notation"], ["REST API", "Data Format"], 0.4)
add("xml", "XML", "other", ["extensible markup language"], ["Data Format", "SOAP"], 0.35)
add("protobuf", "Protobuf", "other", ["protocol buffers", "proto"], ["gRPC", "Serialization"], 0.5)
add("wasm", "WebAssembly", "other", ["webassembly", "wasm"], ["Rust", "C++", "Browser"], 0.5)
add("pwa", "PWA", "other", ["progressive web app", "progressive web application"], ["Frontend", "Mobile"], 0.45)

# ── SOFT SKILLS ──────────────────────────────────────────
add("teamwork", "Teamwork", "soft_skill", ["team collaboration", "collaboration", "cross-functional"], ["Communication", "Leadership"], 0.4)
add("mentoring", "Mentoring", "soft_skill", ["coaching", "mentorship"], ["Leadership"], 0.4)
add("project management", "Project Management", "soft_skill", ["project mgmt", "pm"], ["Agile", "JIRA", "Scrum"], 0.5)
add("presentation", "Presentation Skills", "soft_skill", ["public speaking", "presentations"], ["Communication"], 0.35)
add("stakeholder management", "Stakeholder Management", "soft_skill", ["stakeholder communication"], ["Communication", "Leadership"], 0.4)
add("time management", "Time Management", "soft_skill", ["prioritization"], ["Project Management"], 0.35)
add("code review", "Code Review", "soft_skill", ["peer review", "pr review"], ["Git", "Quality"], 0.5)
add("technical writing", "Technical Writing", "soft_skill", ["tech writing", "documentation writing"], ["Documentation"], 0.45)
add("kanban", "Kanban", "soft_skill", [], ["Agile", "JIRA"], 0.4)

# ── DOMAIN ───────────────────────────────────────────────
add("fintech", "FinTech", "domain", ["financial technology"], ["Finance", "Banking"], 0.5)
add("healthcare", "Healthcare", "domain", ["health tech", "healthtech"], ["HIPAA", "Medical"], 0.5)
add("e-commerce", "E-Commerce", "domain", ["ecommerce", "online retail"], ["Payments", "Stripe"], 0.5)
add("saas", "SaaS", "domain", ["software as a service"], ["Cloud", "Subscription"], 0.55)
add("mobile development", "Mobile Development", "domain", ["mobile dev", "mobile app development"], ["iOS", "Android", "Flutter", "React Native"], 0.65)
add("ios", "iOS", "domain", ["ios development", "iphone development"], ["Swift", "Xcode"], 0.6)
add("android", "Android", "domain", ["android development", "android sdk"], ["Kotlin", "Java"], 0.6)
add("embedded systems", "Embedded Systems", "domain", ["embedded", "firmware", "embedded software"], ["C", "C++", "RTOS"], 0.55)
add("game development", "Game Development", "domain", ["gamedev", "game dev"], ["Unity", "Unreal Engine", "C++"], 0.5)
add("payments", "Payment Integration", "domain", ["stripe", "payment processing", "payment gateway"], ["E-Commerce", "FinTech"], 0.5)
add("cloud computing", "Cloud Computing", "domain", ["cloud infrastructure"], ["AWS", "GCP", "Azure"], 0.7)
add("edge computing", "Edge Computing", "domain", ["edge ai"], ["IoT", "Cloud Computing"], 0.5)
add("iot", "IoT", "domain", ["internet of things"], ["Embedded Systems", "Edge Computing", "MQTT"], 0.5)
add("data warehouse", "Data Warehouse", "domain", ["data warehousing", "dwh"], ["Snowflake", "BigQuery", "Redshift"], 0.6)

# ── CERTIFICATIONS ───────────────────────────────────────
add("aws certified", "AWS Certified", "domain", ["aws certification", "aws solutions architect", "aws developer associate"], ["AWS"], 0.6)
add("azure certified", "Azure Certified", "domain", ["azure certification", "az-900", "az-104", "az-204"], ["Azure"], 0.55)
add("gcp certified", "GCP Certified", "domain", ["google cloud certification"], ["GCP"], 0.5)
add("cka", "CKA", "domain", ["certified kubernetes administrator"], ["Kubernetes"], 0.55)
add("pmp", "PMP", "domain", ["project management professional"], ["Project Management"], 0.45)
add("cissp", "CISSP", "domain", ["certified information systems security professional"], ["Cybersecurity"], 0.5)
add("scrum certification", "Certified Scrum Master", "domain", ["csm", "psm"], ["Scrum", "Agile"], 0.4)

data["version"] = "2.0.0"
data["skills"] = skills

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Taxonomy expanded: {len(skills)} skills (v2.0.0)")
