"""
NeuroSync — ORM models.

Implements blueprint 09 §2 as amended by doc 15 §4 (four tables, not ten) and
doc 10 D-007. Three tables are built here; the fourth
(`skill_taxonomy_overrides`) is deferred — see doc 10 D-007 for why.

Deviations from doc 09's DDL, all deliberate and logged in doc 10 D-007:

* **Primary keys are `VARCHAR(36)`, not `UUID DEFAULT gen_random_uuid()`.**
  `analysis_id` is generated by the application as a truncated UUID
  (`"92bb1053-76d"`, doc 13 §4 D5) and is not a valid UUID value. Typing the
  column as UUID would force a change to the public id format inside the
  persistence task instead of inside the task that owns the contract. String keys
  also let the identical migration run on SQLite, which is what local development
  and the restart probe use.
* **`users.password_hash` is absent.** Auth is magic-link (doc 15 §18); there is
  no password to hash, and a `NOT NULL` column no code can fill is a lie.
* **`feedback.analysis_id` is nullable.** Doc 08 §3.2 documents
  `decision_found: false` for feedback whose analysis is no longer known. A
  `NOT NULL` FK would make that documented response impossible to store.
* **`feedback` carries a snapshot of the decision.** Calibration statistics must
  survive deletion of the analysis row (M2 data-deletion), and the snapshot
  removes a join from the hot `/feedback` path.

JSON columns use `JSONB` on PostgreSQL and generic `JSON` elsewhere.
"""
from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import (
    JSON,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

#: JSONB on PostgreSQL (indexable, binary), plain JSON on every other dialect.
JSONVariant = JSON().with_variant(JSONB, "postgresql")

#: Application-generated ids: uuid4 strings, or the 12-char analysis id.
ID = String(36)


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


class User(Base):
    """Doc 09 §2.1. No rows are written until magic-link auth lands in M2; the
    table exists now so `analyses.user_id` is a real foreign key from the first
    migration rather than a column bolted on later."""

    __tablename__ = "users"

    id: Mapped[str] = mapped_column(ID, primary_key=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    first_name: Mapped[str | None] = mapped_column(String(100))
    last_name: Mapped[str | None] = mapped_column(String(100))
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    is_superuser: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow,
        onupdate=utcnow, server_default=func.now(),
    )

    analyses: Mapped[list["Analysis"]] = relationship(back_populates="user")

    __table_args__ = (Index("idx_users_email", "email"),)


class Analysis(Base):
    """Doc 09 §2.4. The full API response is kept in `payload` — doc 15 §4:
    the report is a document, not a relational entity. The columns beside it are
    the fields that get filtered, aggregated or calibrated against."""

    __tablename__ = "analyses"

    id: Mapped[str] = mapped_column(ID, primary_key=True)
    user_id: Mapped[str | None] = mapped_column(
        ID, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )

    resume_text: Mapped[str] = mapped_column(Text, nullable=False)
    jd_text: Mapped[str] = mapped_column(Text, nullable=False)

    recommendation: Mapped[str] = mapped_column(String(50), nullable=False)
    fit_level: Mapped[str] = mapped_column(String(50), nullable=False)
    overall_score: Mapped[float] = mapped_column(Float, nullable=False)
    shortlist_probability: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    reasoning: Mapped[str] = mapped_column(Text, nullable=False, default="")

    semantic_score: Mapped[float | None] = mapped_column(Float)
    skill_overlap_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    gap_penalty: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    scoring_explanation: Mapped[str] = mapped_column(Text, nullable=False, default="")

    payload: Mapped[dict] = mapped_column(JSONVariant, nullable=False, default=dict)

    processing_time_ms: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow, server_default=func.now()
    )

    user: Mapped["User | None"] = relationship(back_populates="analyses")
    feedback: Mapped["Feedback | None"] = relationship(
        back_populates="analysis", cascade="all, delete-orphan", uselist=False
    )

    __table_args__ = (
        Index("idx_analyses_user", "user_id"),
        Index("idx_analyses_score", "overall_score"),
        # doc 15 §4: composite for history paging, before it is needed.
        Index("idx_analyses_user_created", "user_id", "created_at"),
    )


class Feedback(Base):
    """Doc 09 §2.5. One outcome per analysis (UNIQUE), plus any number of
    orphan reports whose analysis is unknown (`analysis_id IS NULL`) — SQL
    UNIQUE permits repeated NULLs, which is exactly the semantics wanted."""

    __tablename__ = "feedback"

    id: Mapped[str] = mapped_column(ID, primary_key=True)
    analysis_id: Mapped[str | None] = mapped_column(
        ID, ForeignKey("analyses.id", ondelete="CASCADE"), unique=True, nullable=True
    )
    outcome: Mapped[str] = mapped_column(String(50), nullable=False)
    user_notes: Mapped[str] = mapped_column(Text, nullable=False, default="")

    # Decision snapshot — see module docstring.
    score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    shortlist_probability: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    confidence: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    recommendation: Mapped[str] = mapped_column(String(50), nullable=False, default="")
    fit_level: Mapped[str] = mapped_column(String(50), nullable=False, default="")

    is_processed: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=utcnow, server_default=func.now()
    )

    analysis: Mapped["Analysis | None"] = relationship(back_populates="feedback")

    __table_args__ = (
        Index("idx_feedback_outcome", "outcome"),
        Index("idx_feedback_unprocessed", "is_processed"),
    )
